# yaml-language-server: $schema=https://json.schemastore.org/github-action.json
name: "github-issue-reporter"
description: "Generates reports (typically daily) of potentially stale issues or issues that need attention."
inputs:
  reportPath:
    description: "Path of report folder"
    required: false
    default: "reports"
  reportNameTemplate:
    description: "File name template for reports. Can use metacharacters understood by Python strftime."
    required: false
    default: "report-%a.md"
  days:
    description: "How often (in days) reports will be generated. Used to determine what items are new since last report."
    required: false
    default: '1'
  githubToken:
    description: "The Github token for API access."
    required: true
runs:
  using: "composite"
  steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install reporter
      run:
        python -m pip install ghreport
      shell: bash
    - name: Generate report
      run: |
        mkdir -p $INPUT_REPORTPATH
        ghreport -o ${{ inputs.reportPath }}/${{ inputs.reportNameTemplate }} -d ${{ inputs.days }} $GITHUB_REPOSITORY ${{ inputs.githubToken }}
      shell: bash
    - name: Commit report
      id: commit
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "github-actions"
        git add reports
        git commit -m "Daily report update" -a
      shell: bash
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ inputs.githubToken }}
