name: 'Generate Daily Report'

inputs:
  reportPath:
    description: 'Path of report folder'
    required: false
    default: 'reports'
  reportNameTemplate:
    description: 'File name template for reports. Can use metacharacters understood by Python\'s strftime.'
    required: false
    default: 'report-%a.md'
  days:
    description: 'How often (in days) reports will be generated. Used to determine what items are new since last report.'
    required: false
    default: 1

runs:
  using: "composite"
  steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"

    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install reporter
      run:
        python -m pip install ghreport

    - name: Generate report
      run: |
        mkdir -p $env.INPUT_REPORTPATH
        ghreport -o $env.INPUT_REPORTPATH/$env.INPUT_REPORTNAMETEMPLATE -d $env.INPUT_DAYS $env.GITHUB_REPOSITORY ${{ secrets.GITHUB_TOKEN }}

    - name: Commit report
      id: commit
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "github-actions"
        git add reports
        if [-z "$(git status --porcelain)"]; then
           echo "::set-output name=push::false"
        else
           git commit -m "Daily report update" -a
           echo "::set-output name=push::true"
        fi
      shell: bash

    - name: Push changes
      if: steps.commit.outputs.push == 'true'
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
