name: 'Generate Daily Report'

on:
  schedule:
    - cron: '0 6 * * *'  
jobs:
  report:
    runs-on: ubuntu-18.04
    timeout-minutes: 10
    steps:
      - id: report
        uses: gramster/github-reporter@v1
