name: 'Generate Daily Report (manual)'

on:
  workflow_dispatch 
  
jobs:
  report:
    runs-on: ubuntu-18.04
    timeout-minutes: 10
    steps:
      - id: report
        uses: gramster/github-issue-reporter@main
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
        
